# Generated by Django 3.1.1 on 2021-03-02 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('harvests', '0010_auto_20210226_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('date', models.DateTimeField()),
                ('block', models.CharField(blank=True, max_length=16)),
                ('lot', models.CharField(blank=True, max_length=16)),
                ('bunchBatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvests.bunchbatch')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
