# Generated by Django 3.1.1 on 2021-02-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20210224_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='parcelowner',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='parcelowner',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
    ]
