# Generated by Django 3.1.1 on 2021-02-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('harvests', '0004_batchsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('label', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='AI/images/')),
                ('bunches', models.ManyToManyField(to='harvests.Bunch')),
            ],
            options={
                'verbose_name': 'Processed Image',
                'verbose_name_plural': 'Processed Images',
            },
        ),
    ]
