# Generated by Django 3.1.1 on 2021-02-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('name', models.CharField(choices=[('GREEN', 'GREEN'), ('MATURE', 'MATURE'), ('OVERMATURE', 'OVERMATURE'), ('MATURE', 'MATURE'), ('COBS', 'COBS'), ('IMPURITIES', 'IMPURITIES')], max_length=128)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Bunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='harvests.categorybunch')),
            ],
            options={
                'verbose_name': 'Bunch',
                'verbose_name_plural': 'Bunches',
            },
        ),
    ]
