# Generated by Django 3.1.1 on 2021-02-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Green category', 'GREEN'), ('Mature category', 'MATURE'), ('Overmature category', 'OVERMATURE'), ('Mature category', 'MATURE'), ('Cobs category', 'COBS'), ('Impurities category', 'IMPURITIES')], max_length=128)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Bunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='harvests.categorybunch')),
            ],
            options={
                'verbose_name': 'Bunch',
                'verbose_name_plural': 'Bunches',
            },
        ),
    ]
