# Generated by Django 3.1.1 on 2021-02-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0002_auto_20210214_0519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorybunch',
            options={'verbose_name': 'BunchCategory', 'verbose_name_plural': 'BunchCategories'},
        ),
        migrations.AddField(
            model_name='categorybunch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorybunch',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
