# Generated by Django 3.1.1 on 2021-02-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0003_auto_20210215_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'BatchSource',
                'verbose_name_plural': 'BatchSources',
            },
        ),
    ]
