# Generated by Django 3.1.1 on 2021-02-19 21:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0004_batchsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchsource',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Select at least 3 points to delimit a region. When finished, press click twice.', null=True, srid=4326),
        ),
    ]
