# Generated by Django 3.1.1 on 2021-02-24 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0005_auto_20210219_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchSource',
        ),
        migrations.AlterField(
            model_name='bunch',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='harvests.categorybunch'),
        ),
        migrations.AlterField(
            model_name='categorybunch',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
