# Generated by Django 3.1.1 on 2021-02-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0006_auto_20210224_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=64)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('web', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name': 'Harvester',
                'verbose_name_plural': 'Harvesters',
            },
        ),
        migrations.AlterModelOptions(
            name='categorybunch',
            options={'verbose_name': 'Bunch Category', 'verbose_name_plural': 'Bunch Categories'},
        ),
    ]
