# Generated by Django 3.1.1 on 2021-02-25 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0007_auto_20210224_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunch',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='harvests.categorybunch'),
        ),
    ]
