# Generated by Django 3.1.1 on 2021-02-26 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20210224_2245'),
        ('harvests', '0008_auto_20210224_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='BunchBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('bunches', models.ManyToManyField(blank=True, to='harvests.Bunch')),
                ('harvesters', models.ManyToManyField(blank=True, to='harvests.Harvester')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.parcel')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sources.vehicle')),
            ],
            options={
                'verbose_name': 'Bunch Batches',
                'verbose_name_plural': 'Bunch Batches',
            },
        ),
    ]
