# Generated by Django 3.1.1 on 2021-02-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0009_bunchbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunch',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='bunch',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='bunchbatch',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='bunchbatch',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='categorybunch',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='categorybunch',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
    ]
